import { Helmet } from "react-helmet-async";
import "@/styles/pages.css";

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms of Service — ContentForge</title>
        <meta name="description" content="The terms that govern your use of ContentForge." />
        <meta name="robots" content="noindex, follow" />
        <link rel="canonical" href="https://contentforged.lovable.app/terms" />
      </Helmet>
      <div className="lg-app">
        <div className="lg-inner">
          <a href="/" className="lg-back">
            ← Back to ContentForge
          </a>
          <div className="lg-eyebrow">Legal</div>
          <h1 className="lg-title">Terms of Service</h1>
          <p className="lg-updated">Last updated: June 15, 2026</p>
          <div className="lg-body">
            <p>
              These Terms govern your use of ContentForge (the "Service"). By creating an account or
              using the Service, you agree to these Terms.
            </p>

            <h2>The Service</h2>
            <p>
              ContentForge helps you generate, plan, and schedule social media content using AI. The
              Service is currently offered as a paid beta — features, limits, and pricing may change
              as we improve the product, and we'll do our best to communicate material changes in
              advance.
            </p>

            <h2>Accounts</h2>
            <ul>
              <li>
                You must provide a valid email address and keep your login credentials secure.
              </li>
              <li>You're responsible for all activity that happens under your account.</li>
              <li>You must be legally able to enter into these Terms to use the Service.</li>
            </ul>

            <h2>Plans, billing, and quotas</h2>
            <ul>
              <li>Paid plans are billed via Razorpay according to the plan you select.</li>
              <li>
                Each plan includes a generation quota that resets on your billing cycle; usage
                beyond your quota requires an upgrade or your own AI provider key (where supported
                by your plan).
              </li>
              <li>
                Subscriptions can be cancelled at any time from your account settings; access
                continues until the end of the current billing period.
              </li>
            </ul>

            <h2>AI-generated content</h2>
            <ul>
              <li>
                Content is generated by AI models and may occasionally be inaccurate, repetitive, or
                require edits before publishing.
              </li>
              <li>
                You are responsible for reviewing generated content before publishing it, including
                for accuracy, compliance, and tone.
              </li>
              <li>
                You retain ownership of the content you generate using your inputs, subject to the
                terms of any underlying AI providers.
              </li>
            </ul>

            <h2>Acceptable use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Generate or distribute illegal, abusive, or infringing content.</li>
              <li>Attempt to bypass rate limits, quotas, or security controls.</li>
              <li>Resell or sublicense access to the Service without our written consent.</li>
            </ul>

            <h2>Availability and changes</h2>
            <p>
              As a beta product, the Service may have downtime, bugs, or evolving functionality.
              We'll aim to give notice of significant changes that affect your plan or stored
              content, but the Service is provided "as is" without warranties of uninterrupted
              availability.
            </p>

            <h2>Termination</h2>
            <p>
              You may stop using the Service and request account deletion at any time. We may
              suspend or terminate accounts that violate these Terms or that pose a security risk to
              the Service.
            </p>

            <h2>Contact</h2>
            <p>
              Questions about these Terms can be sent to{" "}
              <a href="mailto:support@contentforged.app">support@contentforged.app</a>.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
