// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getSupabaseConfig = () => {
  if (typeof window !== "undefined") {
    const customUrl = localStorage.getItem("contentforge_custom_supabase_url");
    const customKey = localStorage.getItem("contentforge_custom_supabase_anon_key");
    if (customUrl && customKey) {
      return { url: customUrl, key: customKey };
    }
  }
  return {
    url: import.meta.env.VITE_SUPABASE_URL || "",
    key: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "",
  };
};

const config = getSupabaseConfig();

export const supabase = createClient<Database>(config.url, config.key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});